### ISSUE TITLE
Add Aphrodite / Radarr V3 Support

### ISSUE THREAD

**Issue by BinsonBuzz** [RhinoRhys/radarr-collections#106]
Great script - just need some help getting running please!  I'm a python newbie.  So far tried:

(i) installing Python27 to windows
(ii) and I've then run:

```
C:\Python27\python.exe -m pip install requests

C:\Python27\python.exe -m pip install --upgrade pip

C:\Python27\python.exe -m pip install configparser

C:\Python27\python.exe C:\scripts\radarr-collections-master\rcm.py ./config
```

and I get:

`C:\scripts\radarr-collections-master>C:\Python27\python.exe C:\scripts\radarr-collections-master\rcm.py ./config
Traceback (most recent call last):
  File "C:\scripts\radarr-collections-master\rcm.py", line 416, in <module>
    data = api("Radarr")
  File "C:\scripts\radarr-collections-master\rcm.py", line 159, in api
    return response.json()  ## EXIT
  File "C:\Python27\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Help please

**Comment by BinsonBuzz** [comment]
Update: I'm running Aphrodite / Radarr V3.  I installed a quick v2 version and it's working.

Is V3 support in the pipeline soon as this script is exactly what I need!  Thanks

**Comment by BinsonBuzz** [comment]
Closing - as usual it was me being stupid - working now
