### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position blah: character maps to <undefined>

### ISSUE THREAD

**Issue by traubm** [RhinoRhys/radarr-collections#110]
Get this error when hitting collections with foreign names. E.g.:

[21-01-01 13:40:21] 4747: Radarr ID: 4878   TMDB ID: 16364     Robotech: The Shadow Chronicles (2006)                                                      In Collection

[21-01-01 13:40:21] >     ????(??) (ID: 396839): 4 Movies in collection:

Traceback (most recent call last):
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 513, in <module>
    else: tmdb_check(movie["tmdbId"])
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 270, in tmdb_check
    collection_check(col_id, tmdbId)
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 257, in collection_check
    log(words[u'text'][u'other'].format(*payload) +  u"\n")
  File "D:\src\RadarrCollectionandPeopleManager\rcm.py", line 40, in log
    elif sys.version_info[0] == 3: f.write(pay + u"\n")
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-33: character maps to <undefined>

**Comment by traubm** [comment]
Currently working around by un-monitoring  items to stop the collections being added.

**Comment by BluSpoon** [comment]
I have created a PR for better handling of UTF-8

I do not know if this will help your case, but i have just tried adding 16384 on radarr, and running an update.
All movies were grabbed and added.

Maybe pull down #111 and see if it helps you?

**Comment by Bazzu85** [comment]
same problem here with this movie:
https://www.themoviedb.org/movie/185341-rec-4-apocalipsis
