### ISSUE TITLE
Failed to add [Response Code: 400]

### ISSUE THREAD

**Issue by Deadly-Bytes** [RhinoRhys/radarr-collections#113]
I can't seem to get this working. When adding a movie I get `---> Failed to add [Response Code: 400]` This is with radarr v3.1.1.4954

Looks like this is the error radarr is throwing
`2021-05-31 16:29:05.6|Warn|RadarrErrorPipeline|API Error:
BadRequest: Invalid request body. The JSON value could not be converted to System.Boolean. Path: $.monitored | LineNumber: 0 | BytePositionInLine: 20.

[v3.1.1.4954] Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Boolean. Path: $.monitored | LineNumber: 0 | BytePositionInLine: 20.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)`

I tried run this against radarr v0.2.0.1503 and it worked.

**Comment by rob-bc** [comment]
I was just having this same problem. I think the cause is that for the two boolean entries of the Radarr API (monitored, and searchForMovie), they need to be boolean, but this script tries to enter it as a string (eg. should be `true`, but `"true"` is submitted to the API).

I bodged a fix by just hardcoding it in the rcm.py script, so that it looks like this (around line 207 I think):

```
post_data = {u"qualityProfileId" : int(data[index][u'qualityProfileId']),
                         u"rootFolderPath": path,
                         u"monitored" : True,
                         u"addOptions" : {u"searchForMovie" : True}}

```

**Comment by DrAg0n141** [comment]
It works for you now with that? I has still Failed to add [Response Code: 400]

**Comment by rob-bc** [comment]
I made a minor but critical error in the previous post,  the hardcoded value should be `True`, not `true`, as it was in the second example.
If that wasn't you problem, then I'm happy to take a look at your Radarr logs (will have to be at Trace level).

FYI I am already a little out of my depth when it comes to programming so there is probably a more reliable/efficient way to do this!

**Comment by Deadly-Bytes** [comment]
Works! Thank you rob-bc for the fix, and of course RhinoRhys for the script in the first place. Wanted something like this for years (didn't find it till now). Thank you!

**Comment by DrAg0n141** [comment]
`API Error:
BadRequest: Invalid request body. ''' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.: BadRequest: Invalid request body. ''' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.`

`Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. ''' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)`


These are my error with Logs at Trace Level, or you need more? Radarr v3.2.2.5080

**Comment by rob-bc** [comment]
Looks to me like a stray quote mark. Could you share the section of the rcm.py which you edited?

**Comment by DrAg0n141** [comment]
I have edit this under #%% Movie in Database Check Function

> post_data = {u"qualityProfileId" : int(data[index][u'qualityProfileId']),
                         u"rootFolderPath": path,
                         u"monitored" : True,
                         u"addOptions" : {u"searchForMovie" : True}}

**Comment by rob-bc** [comment]
Sorry I can't see anything obvious from my phone, if you can shared your rcm.py file and config file I'll try to have a look when I get to a computer.
