### ISSUE TITLE
AttributeError: 'str' object has no attribute '_make_child'

### ISSUE THREAD

**Issue by pcooney4** [RhinoRhys/radarr-collections#122]
Getting this in docker with the new build.

```

Traceback (most recent call last):

  File "/app/rcm.py", line 300, in <module>

    if not Path.exists(Path.joinpath(config_path, "rcm.conf")): nologfatal(u"\n" + "Error - {}/rcm.conf does not exist.".format(config_path))

  File "/usr/local/lib/python3.9/pathlib.py", line 972, in joinpath

    return self._make_child(args)

AttributeError: 'str' object has no attribute '_make_child'

```

**Comment by pcooney4** [comment]
https://github.com/Roxedus/docker-containers/issues/6

**Comment by pcooney4** [comment]
This is still not fixed.

**Comment by supoman-lei** [comment]
This bug seems to be caused by pathlib
