### ISSUE TITLE
People scanning not working

### ISSUE THREAD

**Issue by pcooney4** [RhinoRhys/radarr-collections#132]
Full scanning works fine, but as this is now more or less built into radarr, not as needed.  People scanning does not appear to be working.  Tried the default example, Quenting, Tom, no luck.

Welcome to Radarr Collection and People Manager by u/RhinoRhys
Auto adding disabled: saving results to file
People only mode: Ignoring Collections
1 monitored People:
[23-01-23 22:28:49] 1:    Tom Hardy (ID: 2524): Monitoring: Acting
[23-01-23 22:28:49] >>    Appeared in 50 Movies:
[23-01-23 22:28:50] >>                     TMDB ID: 45158     A for Andromeda (2006)                                                                                           Adding to Wanted
Traceback (most recent call last):
  File "/app/rcm.py", line 520, in <module>
    person_check(person)
  File "/app/rcm.py", line 291, in person_check
    database_check(movie['id'], white_name, per_json, " - Cast - " + movie[u'character'].title())
  File "/app/rcm.py", line 177, in database_check
    elif stage == 3: index = tmdb_ids.index(int(config[u'adding'][u'profile']))
ValueError: invalid literal for int() with base 10: ''
Total Movies Found: 0
Thank You for using Radarr Collection and People Manager by u/RhinoRhys

Thanks

**Comment by RhinoRhys** [comment]
Hi, your config file is incorrect. The TMDB ID value you have entered under Adding > Profile is not a valid integer
