### ISSUE TITLE
rcm.py exits after finding a match

### ISSUE THREAD

**Issue by happyoccasion** [RhinoRhys/radarr-collections#99]
# python /home/plex/radarr-collections/rcm.py /home/plex/radarr-collections-config -p
Welcome to Radarr Collection and People Manager by u/RhinoRhys

People only mode: Ignoring Collections

Checking 1 monitored People:

[19-03-11 12:35:50] 1:   Michael Haneke (ID: 6011): Monitoring: Directing

[19-03-11 12:35:50] >>    Credited for Directing on 25 Movies:

[19-03-11 12:35:50] >>    Radarr ID: 1385  TMDB ID: 445       Caché (2005)                                                                                                     In Library
[19-03-11 12:35:50] >>    Radarr ID: 1379  TMDB ID: 1791      The Piano Teacher (2001)                                                                                         In Library
[19-03-11 12:35:50] >>    Radarr ID: 1387  TMDB ID: 1987      Benny's Video (1992)                                                                                             In Library
[19-03-11 12:35:50] >>    Radarr ID: 1380  TMDB ID: 10234     Funny Games (1997)                                                                                               In Library
[19-03-11 12:35:50] >>    Radarr ID: 1384  TMDB ID: 30970     Code Unknown (2000)                                                                                              In Library
[19-03-11 12:35:50] >>    Radarr ID: 1383  TMDB ID: 24190     Time of the Wolf (2003)                                                                                          In Library
[19-03-11 12:35:50] >>    Radarr ID: 1381  TMDB ID: 8461      Funny Games (2007)                                                                                               In Library
[19-03-11 12:35:50] >>    Radarr ID: 1378  TMDB ID: 32761     The Seventh Continent (1989)                                                                                     In Library
[19-03-11 12:35:50] >>    Radarr ID: 1388  TMDB ID: 32764     71 Fragments of a Chronology of Chance (1994)                                                                    In Library
[19-03-11 12:35:50] >>    Radarr ID: 1408  TMDB ID: 26891     The Castle (1997)                                                                                                In Library
[19-03-11 12:35:50] >>    Radarr ID: 1382  TMDB ID: 37903     The White Ribbon (2009)                                                                                          In Library
[19-03-11 12:35:50] >>                     TMDB ID: 48336     Lumière and Company (1995)                                                                                       Missing
[19-03-11 12:35:50] >>>                                       ---> Added sucessfully
Traceback (most recent call last):
  File "/home/plex/radarr-collections/rcm.py", line 433, in <module>
    person_check(person)
  File "/home/plex/radarr-collections/rcm.py", line 323, in person_check
    database_check(tmdb_Id, white_name, per_json, role + " - " + job)
  File "/home/plex/radarr-collections/rcm.py", line 279, in database_check
    tmdb_ids.append(post_data['tmdbId'])
TypeError: string indices must be integers, not str
Found 1 Movies

Thank You for using Radarr Collection and People Manager by u/RhinoRhys

**Comment by RhinoRhys** [comment]
Balls, sorry. I knew there was a reason I had that extra letter in there before, I'll add it back in.

**Comment by happyoccasion** [comment]
works now, thanks =)
